### ISSUE TITLE
PK tag doesnt display until hovered over

### ISSUE THREAD

**Issue by HexCodeFFF** [estroBiologist/pluralchum#6] opened 2022-02-26 03:55 UTC
not sure if this is an issue on my end or what
[this plugin](https://github.com/QbDesu/BetterDiscordAddons/blob/potato/Plugins/BetterBotTags/BetterBotTags.plugin.js) modifies the exact thing that you modify but it works instantly so i'd have a look at that
i'll try to learn bdapi and implement some of these myself but for now ill just give it to you lol

**Comment by transdisaster** [comment] 2022-02-26 09:48
The major limitation here is that PC needs to wait for data from the PK server to modify messages, which happens asynchronously. But as far as I know, once that data arrives it should be able to patch messages instantly, including the PK tags. 

Does the problem persist if you switch back and forth between channels?

**Comment by HexCodeFFF** [comment] 2022-02-26 18:11
Hmmm it stopped happening, I'll have to look into this more to find a way to reliably reproduce it

**Comment by estroBiologist** [comment] 2022-02-26 18:34
doesn't sound like a bug, just intended (if admittedly kind of unintuitive) behaviour. PChum caches member data, so proxy patching gets more consistent over time. there's a Clear Cache button in the plugin settings if you want to reproduce the behaviour, but with my current (read: bad) understanding of React, i don't think there's much i can do about it. i'll take another stab at it for 1.1, though.

**Comment by ariagivens** [comment] 2023-09-09 00:16
Fixed by #32

**Closed by ariagivens** 2023-09-09 00:16 UTC
